### ISSUE TITLE
Use darbiadev-shipping-types to build consistent output types across carriers

### ISSUE THREAD

**Issue by shenanigansd** [darbiadev/darbiadev-shipping#6]
Use the standardized objects in darbiadev-shipping-types to be able to provide a consistent return type across the various carrier API implementations.

## Carrier specific issues
- [ ] darbiadev/darbiadev-ups#9
- [ ] darbiadev/darbiadev-fedex#6
- [x] darbiadev/darbiadev-usps#6
